project_name: config-pilot

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/monitor
    binary: config-pilot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: config-pilot-deb
    package_name: config-pilot
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Config Pilot
    homepage: https://github.com/aditirvan/config-pilot
    maintainer: Adhithia Irvan <adhithia.irvan@gmail.com>
    description: Config Pilot - GitOps Configuration Monitor
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: deb-package/etc/config-pilot/config.yaml
        dst: /etc/config-pilot/config.yaml
        type: config
      - src: deb-package/lib/systemd/system/config-pilot.service
        dst: /lib/systemd/system/config-pilot.service
    overrides:
      deb:
        scripts:
          postinstall: deb-package/DEBIAN/postinst
          preremove: deb-package/DEBIAN/prerm

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
